// <auto-generated />
using API.Valorant.Dodle.Infra.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Valorant.Dodle.Infra.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231127132652_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Arsenal", b =>
                {
                    b.Property<int>("IdArma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdArma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArma"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Descricao");

                    b.Property<string>("ImagemArma")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemArma");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<int>("Preco")
                        .HasColumnType("int")
                        .HasColumnName("Preco");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Tipo");

                    b.HasKey("IdArma");

                    b.ToTable("Arsenal", "dbo");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Habilidades", b =>
                {
                    b.Property<int>("IdHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHabilidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabilidade"));

                    b.Property<string>("DescricaoPrimeiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DescricaoPrimeiraHabilidade");

                    b.Property<string>("DescricaoSegundaHabilidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DescricaoSegundaHabilidade");

                    b.Property<string>("DescricaoTerceiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DescricaoTerceiraHabilidade");

                    b.Property<string>("DescricaoUltimaHabildade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("DescricaoUltimaHabildade");

                    b.Property<int>("IdPersonagem")
                        .HasColumnType("int")
                        .HasColumnName("IdPersonagem");

                    b.Property<string>("ImagemPrimeiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemPrimeiraHabilidade");

                    b.Property<string>("ImagemSegundaHabilidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemSegundaHabilidade");

                    b.Property<string>("ImagemTerceiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemTerceiraHabilidade");

                    b.Property<string>("ImagemUltimaHabilidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemUltimaHabilidade");

                    b.Property<string>("PrimeiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("PrimeiraHabilidade");

                    b.Property<string>("SegundaHabilidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("SegundaHabilidade");

                    b.Property<string>("TerceiraHabilidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("TerceiraHabilidade");

                    b.Property<string>("UltimaHabildade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("UltimaHabildade");

                    b.HasKey("IdHabilidade");

                    b.HasIndex("IdPersonagem");

                    b.ToTable("Habilidades", "dbo");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Mapas", b =>
                {
                    b.Property<int>("IdMapa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMapa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMapa"));

                    b.Property<string>("ImagemMapa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemMapa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Região")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Região");

                    b.HasKey("IdMapa");

                    b.ToTable("Mapas", "dbo");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Personagem", b =>
                {
                    b.Property<int>("IdPersonagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPersonagem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersonagem"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("Descricao");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Funcao");

                    b.Property<string>("ImagemPersonagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemPersonagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Regiao");

                    b.HasKey("IdPersonagem");

                    b.ToTable("Personagem", "dbo");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Skin", b =>
                {
                    b.Property<int>("IdSkin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSkin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkin"));

                    b.Property<int>("IdArma")
                        .HasColumnType("int")
                        .HasColumnName("IdArma");

                    b.Property<string>("ImagemSkin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("ImagemSkin");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Nome");

                    b.Property<string>("Pacote")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("Pacote");

                    b.Property<string>("Rara")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Rara");

                    b.HasKey("IdSkin");

                    b.HasIndex("IdArma");

                    b.ToTable("Skin", "dbo");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Habilidades", b =>
                {
                    b.HasOne("API.Valorantdle.Dominio.Entidades.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("IdPersonagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("API.Valorantdle.Dominio.Entidades.Skin", b =>
                {
                    b.HasOne("API.Valorantdle.Dominio.Entidades.Arsenal", "Arsenal")
                        .WithMany()
                        .HasForeignKey("IdArma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arsenal");
                });
#pragma warning restore 612, 618
        }
    }
}
